#!/usr/bin/env bash
# vim: set ft=ruby:

# First pass at a fullscreen terminal application,
# based on Gary Bernhardt's selecta
# http://graysoftinc.com/terminal-tricks/random-access-terminal
#
# 1. Get a fullscreen TTY - $stdout.write "#{CSI}2J"    # clear screen
# 2. read csv
# 3. present in the style of more, vi bindings etc

exec /usr/bin/env ruby --disable-gems -x "$0" $*
#!ruby
# --------------------------------------------------------------------------------

require 'csv'

KEY_CTRL_C = ?\C-c
KEY_CTRL_N = ?\C-n
KEY_CTRL_P = ?\C-p
KEY_CTRL_U = ?\C-u
KEY_CTRL_H = ?\C-h
KEY_CTRL_W = ?\C-w
KEY_CTRL_J = ?\C-j
KEY_CTRL_M = ?\C-m
KEY_DELETE = 127.chr # Equivalent to ?\C-?
CSI = "\e["

# $stdout.write "#{CSI}1;4H"  # move to line 1, character 4
# $stdout.write "s"           # overwrite the 'z'

def csv_read(filename)
  CSV.read(
      filename,
      {headers: true,
      encoding: 'utf-8',
      converters: lambda { |value| (value.nil? || value.downcase == 'null') ? '' : value.strip }})
end

class Screen
  def initialize
    clear_screen
  end

  def clear_screen
    $stdout.write "#{CSI}2J"    # clear screen
    $stdout.write "#{CSI}1;1H"  # move to top left corner
  end

  def save_cursor_position
    $stdout.write "#{CSI}s"     # save cursor position
  end

  def restore_cursor_position
    $stdout.write "#{CSI}u"     # restore cursor position
  end
end

class SheetRender
  def initialize(csv_data)
    @csv_data = csv_data
  end

  def rows
    @csv_data.to_a.map do |row|
      row.each_with_index.map do |cell, i|
        format_cell(cell, max_column_width(i))
      end
    end
  end

  def seperator
    '--------------------------------------------------------------------------------'
  end

  def max_column_width(index)
    lengths = @csv_data.to_a.map { |line| line[index] }
    lengths.map(&:length).max
  end

  def format_cell(value, column_width)
    value + (' ' * (column_width - value.length))
  end

  def line(line)
    line.join(" | ")
  end

  def pretty_output
    formatted_rows = rows
    puts formatted_rows[0].join(' | ')
    puts seperator
    puts formatted_rows[1..-1].map { |row| row.join(' | ') }
  end
end

Screen.new

sample_file = csv_read('sample.csv')
render = SheetRender.new(sample_file)

render.pretty_output

gets # stops program immediately exiting
